### ISSUE TITLE
No errors, but no result, 1.19.2

### ISSUE THREAD

**Issue by rawdr** [Patbox/Image2Map#22]
Having trouble understanding how this plugin works. I got the command to work after changing the permission level, but now when I run the command, it says "Generating image map..." but nothing happens. I've tried it with an empty hand and with a map in hand. When it generates a map does it just put it in your inventory?

I'm running the latest 0.2.3 beta on Minecraft 1.19.2 with Fabric loader 0.14.9. No errors that I can see in the server console. Ubuntu 20.04.5 LTS.

```
[14:05:20] [main/INFO]: [STDOUT]: Loading Image2Map...
[14:05:20] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
```

What am I missing? Thanks.

**Comment by Patbox** [comment]
Please report if it happens on latest

**Comment by rawdr** [comment]
Same result. Here's the command I'm running:
/image2map create dither https://cdn.modrinth.com/data/13RpG7dA/icon.png

It says "Getting image..." and "Converting into maps..." and nothing else happens.
When I do /image2map preview https://cdn.modrinth.com/data/13RpG7dA/icon.png, it brings me into the sky with a box that says "Loading..." and nothing else ever happens. I'm stuck there and have to disconnect from the server. Left shift does nothing.

Here's the list of mods I'm running in case there are known conflicts:
```
cloth-config-8.2.88-fabric.jar
Dynmap-3.4-fabric-1.19.1.jar
fabric-api-0.61.0+1.19.2.jar
floodgate-fabric.jar
Geyser-Fabric.jar
image2map-0.3.0.jar
krypton-0.2.1.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.10.0.jar
LuckPerms-Fabric-5.4.40.jar
minimotd-fabric-mc1.19.2-2.0.9.jar
starlight-1.1.1+fabric.ae22326.jar
textile_backup-2.4.0-1.19.1.jar
```
