### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by end3rchan** [Patbox/Image2Map#23]
When i type in an image url from postimage it says "That doesn't seem to be a valid image!" am i getting my syntax wrong or do i need to use another website? the image url i'm using is https://i.postimg.cc/vmMRX0vv/void.jpg. my command is:
"/image2map create https://i.postimg.cc/vmMRX0vv/void.jpg"

**Comment by Aeldit** [comment]
Try https://i.postimg.cc/ZJvTbgBX/void.jpg?dl=1
