### ISSUE TITLE
Instantly crashing on fabric 1.19.2

### ISSUE THREAD

**Issue by SuccBT** [Patbox/Image2Map#26]
when i hit play on the mc launcher it crashes and says "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'image2map'!"

i'll post the crash report in a file
[crash-2023-03-05_05.32.08-client.txt](https://github.com/TheEssem/Image2Map/files/10891701/crash-2023-03-05_05.32.08-client.txt)

**Comment by Patbox** [comment]
Config looks to be corrupted, but this version is older than whats officially supported
