### ISSUE TITLE
[1.21] Stuck on "Getting image..." when trying to preview

### ISSUE THREAD

**Issue by stringcheeseguy** [Patbox/Image2Map#51]
We can create image maps as normal when doing /image2map create, but when we do /image2map preview, we see "Getting image...", and players aren't sent to the area where they can edit the image. This means that we can't resize our images.

**Comment by CherubicBoot** [comment]
any updates on this?

**Comment by stringcheeseguy** [comment]
Nope, unfortunately still an issue for me.

Something interesting I found out: after turning off and restarting the server, doing "/image2map preview" works once, sending you to the area where you can edit the image. However, once you're there, you can't resize it. And after you exit, doing "/image2map preview" just shows "Getting image..." and nothing happens.
