### ISSUE TITLE
Trying to put maps onto frames causes the game to crash 

### ISSUE THREAD

**Issue by Korkut-yildiz** [Patbox/Image2Map#53]
[crash-2024-07-26_20.29.09-client.txt](https://github.com/user-attachments/files/16394943/crash-2024-07-26_20.29.09-client.txt)
Here is the crash report details if you are interested.

To achieve this crash first I generated an image which is 6 maps (2x3).
Then I put 6 item frames onto sea lanterns
Lastly I right clicked to the top left frame with the bundle
The game crashed and when I loaded back to the game
The image was half printed as in

expected result: (assume x as printed)
x x
x x 
x x
The result after the crash:
x x
x x
(e) (e)

**Comment by Korkut-yildiz** [comment]
I think I should also add the fact that I rescaled my image from 1096 × 1200 pixels to 274 x 300 pixels.

**Comment by Patbox** [comment]
This was fixed on 1.21

**Comment by Korkut-yildiz** [comment]
> This was fixed on 1.21

Cool. If I am not a nuisance may I ask, how did you fix the array overflow exactly. What went wrong there?

**Comment by Patbox** [comment]
It used the width as height by a mistake
