### ISSUE TITLE
Does not have managable permissions

### ISSUE THREAD

**Issue by Merith-TK** [Patbox/Image2Map#8]
so basically, I run a modded server with luckperms. however i want people to have the ability to use the `mapcreate` command, but it is not a node i can set the default group to have

**Comment by scarifyFX** [comment]
use player roles mod instead, its harder but it's better for fabric.

**Comment by ZackKoblenz** [comment]
bump. Currenty running a cobblemon server on fabric and would love the ability to give my mods the ability to create maps without giving everyone these perms
